-- File generated by the BNF Converter (bnfc 2.9.6.2).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module Parsing.SkelSyntax where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Parsing.AbsSyntax as AbsSyntax

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transStellaIdent :: AbsSyntax.StellaIdent -> Result
transStellaIdent x = case x of
  AbsSyntax.StellaIdent string -> failure x

transExtensionName :: AbsSyntax.ExtensionName -> Result
transExtensionName x = case x of
  AbsSyntax.ExtensionName string -> failure x

transMemoryAddress :: AbsSyntax.MemoryAddress -> Result
transMemoryAddress x = case x of
  AbsSyntax.MemoryAddress string -> failure x

transProgram :: AbsSyntax.Program -> Result
transProgram x = case x of
  AbsSyntax.AProgram languagedecl extensions decls -> failure x

transLanguageDecl :: AbsSyntax.LanguageDecl -> Result
transLanguageDecl x = case x of
  AbsSyntax.LanguageCore -> failure x

transExtension :: AbsSyntax.Extension -> Result
transExtension x = case x of
  AbsSyntax.AnExtension extensionnames -> failure x

transDecl :: AbsSyntax.Decl -> Result
transDecl x = case x of
  AbsSyntax.DeclFun annotations stellaident paramdecls returntype throwtype decls expr -> failure x
  AbsSyntax.DeclFunGeneric annotations stellaident stellaidents paramdecls returntype throwtype decls expr -> failure x
  AbsSyntax.DeclTypeAlias stellaident type_ -> failure x
  AbsSyntax.DeclExceptionType type_ -> failure x
  AbsSyntax.DeclExceptionVariant stellaident type_ -> failure x

transLocalDecl :: AbsSyntax.LocalDecl -> Result
transLocalDecl x = case x of
  AbsSyntax.ALocalDecl decl -> failure x

transAnnotation :: AbsSyntax.Annotation -> Result
transAnnotation x = case x of
  AbsSyntax.InlineAnnotation -> failure x

transParamDecl :: AbsSyntax.ParamDecl -> Result
transParamDecl x = case x of
  AbsSyntax.AParamDecl stellaident type_ -> failure x

transReturnType :: AbsSyntax.ReturnType -> Result
transReturnType x = case x of
  AbsSyntax.NoReturnType -> failure x
  AbsSyntax.SomeReturnType type_ -> failure x

transThrowType :: AbsSyntax.ThrowType -> Result
transThrowType x = case x of
  AbsSyntax.NoThrowType -> failure x
  AbsSyntax.SomeThrowType types -> failure x

transType :: AbsSyntax.Type -> Result
transType x = case x of
  AbsSyntax.TypeAuto -> failure x
  AbsSyntax.TypeFun types type_ -> failure x
  AbsSyntax.TypeForAll stellaidents type_ -> failure x
  AbsSyntax.TypeRec stellaident type_ -> failure x
  AbsSyntax.TypeSum type_1 type_2 -> failure x
  AbsSyntax.TypeTuple types -> failure x
  AbsSyntax.TypeRecord recordfieldtypes -> failure x
  AbsSyntax.TypeVariant variantfieldtypes -> failure x
  AbsSyntax.TypeList type_ -> failure x
  AbsSyntax.TypeBool -> failure x
  AbsSyntax.TypeNat -> failure x
  AbsSyntax.TypeUnit -> failure x
  AbsSyntax.TypeTop -> failure x
  AbsSyntax.TypeBottom -> failure x
  AbsSyntax.TypeRef type_ -> failure x
  AbsSyntax.TypeVar stellaident -> failure x

transMatchCase :: AbsSyntax.MatchCase -> Result
transMatchCase x = case x of
  AbsSyntax.AMatchCase pattern_ expr -> failure x

transOptionalTyping :: AbsSyntax.OptionalTyping -> Result
transOptionalTyping x = case x of
  AbsSyntax.NoTyping -> failure x
  AbsSyntax.SomeTyping type_ -> failure x

transPatternData :: AbsSyntax.PatternData -> Result
transPatternData x = case x of
  AbsSyntax.NoPatternData -> failure x
  AbsSyntax.SomePatternData pattern_ -> failure x

transExprData :: AbsSyntax.ExprData -> Result
transExprData x = case x of
  AbsSyntax.NoExprData -> failure x
  AbsSyntax.SomeExprData expr -> failure x

transPattern :: AbsSyntax.Pattern -> Result
transPattern x = case x of
  AbsSyntax.PatternCastAs pattern_ type_ -> failure x
  AbsSyntax.PatternAsc pattern_ type_ -> failure x
  AbsSyntax.PatternVariant stellaident patterndata -> failure x
  AbsSyntax.PatternInl pattern_ -> failure x
  AbsSyntax.PatternInr pattern_ -> failure x
  AbsSyntax.PatternTuple patterns -> failure x
  AbsSyntax.PatternRecord labelledpatterns -> failure x
  AbsSyntax.PatternList patterns -> failure x
  AbsSyntax.PatternCons pattern_1 pattern_2 -> failure x
  AbsSyntax.PatternFalse -> failure x
  AbsSyntax.PatternTrue -> failure x
  AbsSyntax.PatternUnit -> failure x
  AbsSyntax.PatternInt integer -> failure x
  AbsSyntax.PatternSucc pattern_ -> failure x
  AbsSyntax.PatternVar stellaident -> failure x

transLabelledPattern :: AbsSyntax.LabelledPattern -> Result
transLabelledPattern x = case x of
  AbsSyntax.ALabelledPattern stellaident pattern_ -> failure x

transBinding :: AbsSyntax.Binding -> Result
transBinding x = case x of
  AbsSyntax.ABinding stellaident expr -> failure x

transExpr :: AbsSyntax.Expr -> Result
transExpr x = case x of
  AbsSyntax.Sequence expr1 expr2 -> failure x
  AbsSyntax.Assign expr1 expr2 -> failure x
  AbsSyntax.If expr1 expr2 expr3 -> failure x
  AbsSyntax.Let patternbindings expr -> failure x
  AbsSyntax.LetRec patternbindings expr -> failure x
  AbsSyntax.TypeAbstraction stellaidents expr -> failure x
  AbsSyntax.LessThan expr1 expr2 -> failure x
  AbsSyntax.LessThanOrEqual expr1 expr2 -> failure x
  AbsSyntax.GreaterThan expr1 expr2 -> failure x
  AbsSyntax.GreaterThanOrEqual expr1 expr2 -> failure x
  AbsSyntax.Equal expr1 expr2 -> failure x
  AbsSyntax.NotEqual expr1 expr2 -> failure x
  AbsSyntax.TypeAsc expr type_ -> failure x
  AbsSyntax.TypeCast expr type_ -> failure x
  AbsSyntax.Abstraction paramdecls expr -> failure x
  AbsSyntax.Variant stellaident exprdata -> failure x
  AbsSyntax.Match expr matchcases -> failure x
  AbsSyntax.List exprs -> failure x
  AbsSyntax.Add expr1 expr2 -> failure x
  AbsSyntax.Subtract expr1 expr2 -> failure x
  AbsSyntax.LogicOr expr1 expr2 -> failure x
  AbsSyntax.Multiply expr1 expr2 -> failure x
  AbsSyntax.Divide expr1 expr2 -> failure x
  AbsSyntax.LogicAnd expr1 expr2 -> failure x
  AbsSyntax.Ref expr -> failure x
  AbsSyntax.Deref expr -> failure x
  AbsSyntax.Application expr exprs -> failure x
  AbsSyntax.TypeApplication expr types -> failure x
  AbsSyntax.DotRecord expr stellaident -> failure x
  AbsSyntax.DotTuple expr integer -> failure x
  AbsSyntax.Tuple exprs -> failure x
  AbsSyntax.Record bindings -> failure x
  AbsSyntax.ConsList expr1 expr2 -> failure x
  AbsSyntax.Head expr -> failure x
  AbsSyntax.IsEmpty expr -> failure x
  AbsSyntax.Tail expr -> failure x
  AbsSyntax.Panic -> failure x
  AbsSyntax.Throw expr -> failure x
  AbsSyntax.TryCatch expr1 pattern_ expr2 -> failure x
  AbsSyntax.TryWith expr1 expr2 -> failure x
  AbsSyntax.TryCastAs expr1 type_ pattern_ expr2 expr3 -> failure x
  AbsSyntax.Inl expr -> failure x
  AbsSyntax.Inr expr -> failure x
  AbsSyntax.Succ expr -> failure x
  AbsSyntax.LogicNot expr -> failure x
  AbsSyntax.Pred expr -> failure x
  AbsSyntax.IsZero expr -> failure x
  AbsSyntax.Fix expr -> failure x
  AbsSyntax.NatRec expr1 expr2 expr3 -> failure x
  AbsSyntax.Fold type_ expr -> failure x
  AbsSyntax.Unfold type_ expr -> failure x
  AbsSyntax.ConstTrue -> failure x
  AbsSyntax.ConstFalse -> failure x
  AbsSyntax.ConstUnit -> failure x
  AbsSyntax.ConstInt integer -> failure x
  AbsSyntax.ConstMemory memoryaddress -> failure x
  AbsSyntax.Var stellaident -> failure x

transPatternBinding :: AbsSyntax.PatternBinding -> Result
transPatternBinding x = case x of
  AbsSyntax.APatternBinding pattern_ expr -> failure x

transVariantFieldType :: AbsSyntax.VariantFieldType -> Result
transVariantFieldType x = case x of
  AbsSyntax.AVariantFieldType stellaident optionaltyping -> failure x

transRecordFieldType :: AbsSyntax.RecordFieldType -> Result
transRecordFieldType x = case x of
  AbsSyntax.ARecordFieldType stellaident type_ -> failure x

transTyping :: AbsSyntax.Typing -> Result
transTyping x = case x of
  AbsSyntax.ATyping expr type_ -> failure x
